apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
  template: # We are defining the pod that the deployment manage
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - name: backend
          image: njadric/eadca2_backend
          ports:
            - containerPort: 80
