apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
  template: # We are defining the pod that the deployment manage
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: njadric/eadca2_frontend
          ports:
            - containerPort: 80
